### PR TITLE
WIP: Migrated ranking class

### PR DESCRIPTION
**Pull request by mrcage**
dbquery still needs to be refactored

### CODE REVIEW

**Comment by mrcage** [comment]
No merge yet, its a work in progess

**Comment by glaubinix** [comment]
@mrcage is there anything still missing here? Not sure whether this is ok to review/merge as the title still says WIP

**Comment by mrcage** [comment]
There are still some dbquery calls left, but unfortunately i am currently not finding the time to work on these.... can you have a look, or merge it and we do the remaining queries later?

**Comment by mrcage** [comment]
The current state of the branch is fine, everything should work, its just not complete in terms of dbquery migration

**Comment by glaubinix** [comment]
Yeah, that's fine. I'll go ahead and merge this for now. Will avoid further merge conflicts and either of us can pick this up once we get there.

**Pull request merged**
