### PR TITLE
Webpack

### PR DESCRIPTION
**Pull request by mrcage**
Using webpack (with the help of laravel-mix) to better organize javascript and CSS asset files.

### CODE REVIEW

**Comment by glaubinix** [comment]
Can you add the frontend build as a step to the CI run? Should probably also define somewhere which node version we are using for this.

**Comment by mrcage** [comment]
Ok, will try do to that. Using npm 7.19.1 (node v16.1.0)

**Comment by glaubinix** [comment]
I thinks something like this should work for the setup

```
    client-build:
        name: Client Build
        runs-on: "ubuntu-latest"
        strategy:
            matrix:
                node: [16.1]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
```

**Comment by mrcage** [comment]
done

**Comment by glaubinix** [comment]
I think this is a good start. Before we add to many additional dependencies we should probably discuss what we want to do with JS.

I noticed that the build result is currently part of the repository. This definitely works as long as we mostly focus on updating the PHP code but will lead to merge conflicts once multiple people edit JS or CSS. It is also one step that people could forget when contributing. Long term we should find a solution that ideally builds the JS/CSS as part of the build process which we then reuse on the production servers and add the build folder to the gitignore.

**Comment by mrcage** [comment]
Agree with you. No plans at the moment to add any specific js libs/frameworks, just more of a cleanup to simplify code.
And yes, in case we work more on js, the built assets should be handled separately as suggested.

**Pull request merged**
