### PR TITLE
Added MailSenderService as replacement for mail class

### PR DESCRIPTION
**Pull request by mrcage**

### CODE REVIEW

**Comment by glaubinix** [comment]
👍 I think long term it might be helpful to switch to something like symfony/mailer which has helpful features like don't sent emails in test or send all emails in your local environment to the same email address to make sure you don't send emails to others by accident.

**Comment by mrcage** [comment]
That was actually my idea; I've added mail sending using swiftmailer in the second commit. SMTP Configuration via configuration page in admin panel. I am usually using https://mailtrap.io/ for testing emails

**Comment by glaubinix** [comment]
That's great!

**Comment by mrcage** [comment]
image
image

**Pull request merged**
